- name: Ejecutar Ingesta Capa Bronze
      run: python src/bronze/ingest_bcra_bronze.py

    - name: Ejecutar Transformación Capa Silver
      run: python src/silver/transform_bcra_silver.py

    - name: Ejecutar Agregación Capa Gold
      run: python src/gold/transform_bcra_gold.py
